# How to use:
# ansible-playbook -u <user-name> --key-file '<key-file>' -i '<host-ip>,' basic-env.yml
#
# Ex: ansible-playbook -u ubuntu --key-file '/home/david74/david74-aws.pem' -i '13.115.245.247,' basic-env.yml
---
- hosts: "tag_Purpose_{{ PURPOSE }}:&tag_Environment_{{ ENV }}"
  remote_user: ubuntu
  become: yes
  become_user: root
  roles:
    - install-docker-ce
    - install-pip
    - install-awscli
    - install-docker-py
    - install-ntp
    - install-aws-ecr-helper
    - install-ssh-key
    - update-hostname-with-ec2-tag
    - install-aws-cloudwatch-agent
    - disable-auto-upgrade